FROM oven/bun

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY package.json bun.lockb turbo.json ./
COPY apps/web/package.json apps/web/
COPY packages packagesps

RUN bun install 

COPY apps/web ./apps/web

RUN bun run generate:db
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD ["bun", "start:frontend"]