FROM oven/bun

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY package.json bun.lockb turbo.json ./
COPY apps/frontend/package.json apps/frontend/
COPY packages packages

RUN bun install 

COPY apps/frontend ./apps/frontend

RUN bun run generate:db
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD ["bun", "start:frontend"]