FROM oven/bun

WORKDIR /usr/src/app

COPY package.json bun.lockb turbo.json ./
COPY apps/backend/package.json apps/backend/
COPY packages packages

RUN bun install

COPY apps/backend ./apps/backend

RUN bun run generate:db

EXPOSE 8080

CMD ["bun", "start:backend"]
